# Generated by Django 3.2.8 on 2021-12-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
