# Generated by Django 3.2.8 on 2021-12-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
